version: "3"
services:
  app:
    image: app
    build:
      context: .
    volumes:
      - ./:/usr/src/
    ports:
      - 3000:3000
    environment:
      REDIS_URL: redis://redis:6379/0
    tty: true
  
  redis:
    image: redis:alpine
    volumes:
      - redis:/data

  db:
    image: postgres:11.5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  redis:
  postgres:
